services:
  postgres-api:
    image: postgres:17-alpine
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-sal}
    ports:
      - '5432:${DB_PORT:-5432}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: nestjs-dev
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      DB_HOST: postgres-api
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-sal}
      SECRET: ${SECRET}
      DB_PORT: ${DB_PORT:-5432}
    volumes:
      - ./api:/app
      - /app/node_modules
    
    depends_on:
      - postgres-api
  
  front:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - "${UI_PORT:-3001}:3001"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  postgres_data:
